/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minitestpesonalidadclips;
import net.sf.clipsrules.jni.*;
/**
 *
 * @author KLEBER PUCHA
 */
public class TestPerosnalidad extends javax.swing.JFrame {
    private Environment clips;
    /**
     * Creates new form TestPerosnalidad
     */
    public TestPerosnalidad() {
        initComponents();
        clips = new Environment();
        clips.load("personalidad.clp");
        System.out.println("Hola Mundo Clips");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInstrucciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelpreguntas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        l1 = new javax.swing.JComboBox<>();
        l2 = new javax.swing.JComboBox<>();
        l3 = new javax.swing.JComboBox<>();
        l4 = new javax.swing.JComboBox<>();
        l5 = new javax.swing.JComboBox<>();
        l6 = new javax.swing.JComboBox<>();
        l7 = new javax.swing.JComboBox<>();
        l8 = new javax.swing.JComboBox<>();
        l9 = new javax.swing.JComboBox<>();
        l10 = new javax.swing.JComboBox<>();
        o2 = new javax.swing.JComboBox<>();
        o3 = new javax.swing.JComboBox<>();
        o4 = new javax.swing.JComboBox<>();
        o5 = new javax.swing.JComboBox<>();
        o6 = new javax.swing.JComboBox<>();
        o7 = new javax.swing.JComboBox<>();
        o8 = new javax.swing.JComboBox<>();
        o9 = new javax.swing.JComboBox<>();
        o10 = new javax.swing.JComboBox<>();
        o1 = new javax.swing.JComboBox<>();
        g1 = new javax.swing.JComboBox<>();
        g2 = new javax.swing.JComboBox<>();
        g3 = new javax.swing.JComboBox<>();
        g4 = new javax.swing.JComboBox<>();
        g5 = new javax.swing.JComboBox<>();
        g6 = new javax.swing.JComboBox<>();
        g7 = new javax.swing.JComboBox<>();
        g8 = new javax.swing.JComboBox<>();
        g9 = new javax.swing.JComboBox<>();
        g10 = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JComboBox<>();
        b2 = new javax.swing.JComboBox<>();
        b3 = new javax.swing.JComboBox<>();
        b4 = new javax.swing.JComboBox<>();
        b5 = new javax.swing.JComboBox<>();
        b6 = new javax.swing.JComboBox<>();
        b7 = new javax.swing.JComboBox<>();
        b8 = new javax.swing.JComboBox<>();
        b9 = new javax.swing.JComboBox<>();
        b10 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bntconsultar = new javax.swing.JButton();
        txtrespuesta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInstrucciones.setBackground(new java.awt.Color(255, 255, 255));
        panelInstrucciones.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("TEST DE PERSONALIDAD");

        jLabel2.setText("PARA ESTE TEST SE DEBE ESCOGER UN VALOR DE ENTRE 1 A 4, SISNDO 1 ELE Q ME NOS ME GUSTA Y 4 EL QUE MAS ME GUSTA");

        jLabel3.setText("LION - BEAVER- OTTER- GOLDEN RETRIVER");

        javax.swing.GroupLayout panelInstruccionesLayout = new javax.swing.GroupLayout(panelInstrucciones);
        panelInstrucciones.setLayout(panelInstruccionesLayout);
        panelInstruccionesLayout.setHorizontalGroup(
            panelInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstruccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)))
        );
        panelInstruccionesLayout.setVerticalGroup(
            panelInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstruccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelpreguntas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("PREGUNTAS 1");

        jLabel6.setText("PREGUNTAS 2");

        jLabel7.setText("PREGUNTAS 3");

        jLabel8.setText("PREGUNTAS 4");

        jLabel9.setText("PREGUNTAS 5");

        jLabel10.setText("PREGUNTAS 6");

        jLabel11.setText("PREGUNTAS 7");

        jLabel12.setText("PREGUNTAS 8");

        jLabel13.setText("PREGUNTAS 9");

        jLabel14.setText("PREGUNTAS 10");

        l1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le gusta la autoridad", "1", "2", "3", "4" }));

        l2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toma la carga", "1", "2", "3", "4" }));

        l3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Determinado", "1", "2", "3", "4" }));

        l4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intenta nuevas ideas", "1", "2", "3", "4" }));

        l5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Competitivo", "1", "2", "3", "4" }));

        l6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solucionador de problemas", "1 ", "2", "3", "4" }));

        l7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productivo", "1", "2", "3", "4" }));

        l8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Audaz", "1", "2", "3", "4" }));

        l9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tomador de decisiones", "1", "2", "3", "4" }));

        l10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persistente", "1", "2", "3", "4" }));

        o2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entusiasta", "1", "2", "3", "4" }));
        o2.setMinimumSize(new java.awt.Dimension(126, 20));
        o2.setPreferredSize(new java.awt.Dimension(126, 20));

        o3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entusiasta", "1", "2", "3", "4" }));
        o3.setMinimumSize(new java.awt.Dimension(126, 20));
        o3.setPreferredSize(new java.awt.Dimension(126, 20));

        o4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entusiasta", "1", "2", "3", "4" }));
        o4.setMinimumSize(new java.awt.Dimension(126, 20));
        o4.setPreferredSize(new java.awt.Dimension(126, 20));

        o5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entusiasta", "1", "2", "3", "4" }));
        o5.setMinimumSize(new java.awt.Dimension(126, 20));
        o5.setPreferredSize(new java.awt.Dimension(126, 20));

        o6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entusiasta", "1", "2", "3", "4" }));
        o6.setMinimumSize(new java.awt.Dimension(126, 20));
        o6.setPreferredSize(new java.awt.Dimension(126, 20));

        o7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entusiasta", "1", "2", "3", "4" }));
        o7.setMinimumSize(new java.awt.Dimension(126, 20));
        o7.setPreferredSize(new java.awt.Dimension(126, 20));

        o8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entusiasta", "1", "2", "3", "4" }));
        o8.setMinimumSize(new java.awt.Dimension(126, 20));
        o8.setPreferredSize(new java.awt.Dimension(126, 20));

        o9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entusiasta", "1", "2", "3", "4" }));
        o9.setMinimumSize(new java.awt.Dimension(126, 20));
        o9.setPreferredSize(new java.awt.Dimension(126, 20));

        o10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entusiasta", "1", "2", "3", "4" }));
        o10.setMinimumSize(new java.awt.Dimension(126, 20));
        o10.setPreferredSize(new java.awt.Dimension(126, 20));

        o1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entusiasta", "1", "2", "3", "4" }));
        o1.setMinimumSize(new java.awt.Dimension(126, 20));
        o1.setPreferredSize(new java.awt.Dimension(126, 20));

        g1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentimientos sensitivos", "1", "2", "3", "4" }));

        g2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentimientos sensitivos", "1", "2", "3", "4" }));

        g3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentimientos sensitivos", "1", "2", "3", "4" }));

        g4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentimientos sensitivos", "1", "2", "3", "4" }));

        g5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentimientos sensitivos", "1", "2", "3", "4" }));

        g6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentimientos sensitivos", "1", "2", "3", "4" }));

        g7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentimientos sensitivos", "1", "2", "3", "4" }));

        g8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentimientos sensitivos", "1", "2", "3", "4" }));

        g9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentimientos sensitivos", "1", "2", "3", "4" }));

        g10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentimientos sensitivos", "1", "2", "3", "4" }));

        b1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le gusta la instrucción", "1", "2", "3", "4" }));

        b2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le gusta la instrucción", "1", "2", "3", "4" }));

        b3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le gusta la instrucción", "1", "2", "3", "4" }));

        b4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le gusta la instrucción", "1", "2", "3", "4" }));

        b5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le gusta la instrucción", "1", "2", "3", "4" }));

        b6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le gusta la instrucción", "1", "2", "3", "4" }));

        b7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le gusta la instrucción", "1", "2", "3", "4" }));

        b8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le gusta la instrucción", "1", "2", "3", "4" }));

        b9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le gusta la instrucción", "1", "2", "3", "4" }));

        b10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Le gusta la instrucción", "1", "2", "3", "4" }));

        jLabel15.setText("LION");

        jLabel16.setText("OTTER");

        jLabel17.setText("GOLDEN RETRIVER");

        jLabel18.setText("BEAVER");

        javax.swing.GroupLayout panelpreguntasLayout = new javax.swing.GroupLayout(panelpreguntas);
        panelpreguntas.setLayout(panelpreguntasLayout);
        panelpreguntasLayout.setHorizontalGroup(
            panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpreguntasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(l1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(l2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(l3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(l4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(l5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(l7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(l8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(l9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(o5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(o6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(o7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(o8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(o9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(o10, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g10, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpreguntasLayout.createSequentialGroup()
                        .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panelpreguntasLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel15)
                .addGap(141, 141, 141)
                .addComponent(jLabel16)
                .addGap(98, 98, 98)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(75, 75, 75))
        );
        panelpreguntasLayout.setVerticalGroup(
            panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpreguntasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelpreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        bntconsultar.setText("Consultar");
        bntconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntconsultarActionPerformed(evt);
            }
        });

        txtrespuesta.setText("R//......");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntconsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtrespuesta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("INGRESE SU NOMBRE :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelInstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelpreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelpreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntconsultarActionPerformed
         clips.reset();
         clips.eval("(assert(pregunta1 "+txtnombre.getText()+" "+l1.getSelectedItem()+" "+o1.getSelectedItem()+" "+g1.getSelectedItem()+" "+b1.getSelectedItem()+"))");
         clips.eval("(assert(pregunta2 "+txtnombre.getText()+" "+l2.getSelectedItem()+" "+o2.getSelectedItem()+" "+g2.getSelectedItem()+" "+b2.getSelectedItem()+"))");
         clips.eval("(assert(pregunta3 "+txtnombre.getText()+" "+l3.getSelectedItem()+" "+o3.getSelectedItem()+" "+g3.getSelectedItem()+" "+b3.getSelectedItem()+"))");
         clips.eval("(assert(pregunta4 "+txtnombre.getText()+" "+l4.getSelectedItem()+" "+o4.getSelectedItem()+" "+g4.getSelectedItem()+" "+b4.getSelectedItem()+"))");
         clips.eval("(assert(pregunta5 "+txtnombre.getText()+" "+l5.getSelectedItem()+" "+o5.getSelectedItem()+" "+g5.getSelectedItem()+" "+b5.getSelectedItem()+"))");
         clips.eval("(assert(pregunta6 "+txtnombre.getText()+" "+l6.getSelectedItem()+" "+o6.getSelectedItem()+" "+g6.getSelectedItem()+" "+b6.getSelectedItem()+"))");
         clips.eval("(assert(pregunta7 "+txtnombre.getText()+" "+l7.getSelectedItem()+" "+o7.getSelectedItem()+" "+g7.getSelectedItem()+" "+b7.getSelectedItem()+"))");
         clips.eval("(assert(pregunta8 "+txtnombre.getText()+" "+l8.getSelectedItem()+" "+o8.getSelectedItem()+" "+g8.getSelectedItem()+" "+b8.getSelectedItem()+"))");
         clips.eval("(assert(pregunta9 "+txtnombre.getText()+" "+l9.getSelectedItem()+" "+o9.getSelectedItem()+" "+g9.getSelectedItem()+" "+b9.getSelectedItem()+"))");
         clips.eval("(assert(pregunta10 "+txtnombre.getText()+" "+l10.getSelectedItem()+" "+o10.getSelectedItem()+" "+g10.getSelectedItem()+" "+b10.getSelectedItem()+"))");
         clips.run();
        String respuesta = clips.getInputBuffer();
        System.out.println(respuesta);
        this.txtrespuesta.setText(respuesta);
    }//GEN-LAST:event_bntconsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestPerosnalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestPerosnalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestPerosnalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestPerosnalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestPerosnalidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> b1;
    private javax.swing.JComboBox<String> b10;
    private javax.swing.JComboBox<String> b2;
    private javax.swing.JComboBox<String> b3;
    private javax.swing.JComboBox<String> b4;
    private javax.swing.JComboBox<String> b5;
    private javax.swing.JComboBox<String> b6;
    private javax.swing.JComboBox<String> b7;
    private javax.swing.JComboBox<String> b8;
    private javax.swing.JComboBox<String> b9;
    private javax.swing.JButton bntconsultar;
    private javax.swing.JComboBox<String> g1;
    private javax.swing.JComboBox<String> g10;
    private javax.swing.JComboBox<String> g2;
    private javax.swing.JComboBox<String> g3;
    private javax.swing.JComboBox<String> g4;
    private javax.swing.JComboBox<String> g5;
    private javax.swing.JComboBox<String> g6;
    private javax.swing.JComboBox<String> g7;
    private javax.swing.JComboBox<String> g8;
    private javax.swing.JComboBox<String> g9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> l1;
    private javax.swing.JComboBox<String> l10;
    private javax.swing.JComboBox<String> l2;
    private javax.swing.JComboBox<String> l3;
    private javax.swing.JComboBox<String> l4;
    private javax.swing.JComboBox<String> l5;
    private javax.swing.JComboBox<String> l6;
    private javax.swing.JComboBox<String> l7;
    private javax.swing.JComboBox<String> l8;
    private javax.swing.JComboBox<String> l9;
    private javax.swing.JComboBox<String> o1;
    private javax.swing.JComboBox<String> o10;
    private javax.swing.JComboBox<String> o2;
    private javax.swing.JComboBox<String> o3;
    private javax.swing.JComboBox<String> o4;
    private javax.swing.JComboBox<String> o5;
    private javax.swing.JComboBox<String> o6;
    private javax.swing.JComboBox<String> o7;
    private javax.swing.JComboBox<String> o8;
    private javax.swing.JComboBox<String> o9;
    private javax.swing.JPanel panelInstrucciones;
    private javax.swing.JPanel panelpreguntas;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JLabel txtrespuesta;
    // End of variables declaration//GEN-END:variables
}
